steps:
  - name: 'gradle'
    args:
      - ./gradlew
      - clean
      - build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image:late', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cicd-test-ar/cicd-image:late' ]

options:
  logging: CLOUD_LOGGING_ONLY